use CENTRE_SPORTIF

-- REQUETES AVEC FONCTIONS D’AGREGATION --

-- 1 --
SELECT count(*) AS NbFemmes
FROM INSCRIT
WHERE Sexe ='F'

-- 2 --
SELECT count(*) AS NbFemmes, MAX (Age) AS MaxAge, MIN (Age) AS MinAge
FROM INSCRIT
WHERE Sexe ='H'

-- 3 --
SELECT count(*) AS NbInsctritsNatation
FROM PARTICIPATION
WHERE NomCours ='NatationI' OR NomCours ='NatationII'

-- 4 --
SELECT Max (INSCRIT.Age) AS AgeMaxSalAS
FROM PARTICIPATION JOIN INSCRIT ON PARTICIPATION.Nocarte = INSCRIT.Nocarte
WHERE NomCours ='Salsa'

-- 5 --
SELECT count(*) AS NbFemmesNatationOrAquaGym , AVG (INSCRIT.Age) AverageAge
FROM PARTICIPATION JOIN INSCRIT ON PARTICIPATION.Nocarte = INSCRIT.Nocarte
WHERE Sexe ='F' AND NomCours ='NatationI' OR NomCours ='NatationII' OR NomCours ='Aquagym'

-- 6 --
SELECT count(*) AS NbCoursSalle3
FROM PLANNING
WHERE Lieu ='SalleIII'

-- 7 --
SELECT NomCours , count(*) AS NbParticipants
FROM PARTICIPATION
GROUP BY NomCours

-- 8 --
SELECT NomCours , count(*) AS NbParticipants , AVG (INSCRIT.Age) AverageAge
FROM PARTICIPATION JOIN INSCRIT ON PARTICIPATION.Nocarte = INSCRIT.Nocarte
GROUP BY NomCours

-- 9 --
SELECT Lieu, Jour , count(*) AS NbCours
FROM PLANNING
GROUP BY Lieu,Jour
ORDER BY Lieu

-- 10 --
SELECT COURS.NomCours, count(*) AS NbParticipants
FROM PARTICIPATION JOIN COURS ON PARTICIPATION.NomCours = COURS.NomCours
WHERE COURS.Niveau='Facile'
GROUP BY COURS.NomCours

-- 11 --
SELECT INSCRIT.Nom, INSCRIT.Nocarte, count(PARTICIPATION.NomCours) AS NbCoursFrequente
FROM PARTICIPATION RIGHT JOIN INSCRIT ON PARTICIPATION.Nocarte = INSCRIT.Nocarte
GROUP BY INSCRIT.Nocarte, INSCRIT.Nom

-- 12 --
SELECT COURS.NomCours, count(*) AS NbParticipants
FROM PARTICIPATION JOIN COURS ON PARTICIPATION.NomCours = COURS.NomCours
GROUP BY COURS.NomCours
HAVING count(*) > 5

-- 13 --
SELECT Jour, Heure, count(*) AS NbCoursSimultane
FROM PLANNING 
GROUP BY Jour, Heure
HAVING count(*) > 1

-- 14 --
SELECT PARTICIPATION.NomCours , AVG (INSCRIT.Age) AverageAge
FROM PARTICIPATION JOIN INSCRIT ON PARTICIPATION.Nocarte = INSCRIT.Nocarte
GROUP BY PARTICIPATION.NomCours
HAVING AVG (Age) >30

-- 15 --
SELECT COURS.Enseignant, count(DISTINCT PLANNING.Jour) AS NbJoursEnseigne
FROM COURS JOIN PLANNING ON COURS.NomCours = PLANNING.NomCours
GROUP BY COURS.Enseignant
HAVING count(DISTINCT PLANNING.Jour) > 2

-- 16 --
SELECT INSCRIT.Nom,INSCRIT.Nocarte, count(DISTINCT COURS.Enseignant) AS NbDistinctEnseignants
FROM PARTICIPATION JOIN INSCRIT ON PARTICIPATION.Nocarte = INSCRIT.Nocarte JOIN COURS ON PARTICIPATION.NomCours = COURS.NomCours
GROUP BY INSCRIT.Nom,INSCRIT.Nocarte
HAVING count(DISTINCT COURS.Enseignant) < 4


-- REQUETES IMBRIQUEES/COMPLEXES --

-- 17 --
SELECT Nom,Age
FROM INSCRIT
WHERE Age=(	SELECT MIN (Age)
			FROM INSCRIT)

-- 18 --
SELECT Nom,Age
FROM INSCRIT
WHERE Age=(	SELECT Age
			FROM INSCRIT
			WHERE Nom='Bonnard')

-- 19 --
SELECT NomCours, count(*) as NbParticipants
FROM PARTICIPATION
GROUP BY NomCours
HAVING count(*) > (	SELECT count(*) as NbParticipants
						FROM PARTICIPATION
						WHERE NomCours='Aerobic')

-- 20 --
SELECT PARTICIPATION.NomCours, AVG(INSCRIT.Age) as AverageAge
FROM PARTICIPATION JOIN INSCRIT ON PARTICIPATION.Nocarte = INSCRIT.Nocarte
GROUP BY PARTICIPATION.NomCours
HAVING AVG(INSCRIT.Age) =	(SELECT AVG(INSCRIT.Age) as NbParticipants
							 FROM PARTICIPATION JOIN INSCRIT ON PARTICIPATION.Nocarte = INSCRIT.Nocarte
							 WHERE NomCours='Salsa')

-- 21a --
SELECT INSCRIT.Nom,INSCRIT.Nocarte
FROM PARTICIPATION JOIN INSCRIT ON PARTICIPATION.Nocarte = INSCRIT.Nocarte
WHERE PARTICIPATION.NomCours='Salsa' AND INSCRIT.Nocarte IN (	SELECT INSCRIT.Nocarte
																FROM PARTICIPATION JOIN INSCRIT ON PARTICIPATION.Nocarte = INSCRIT.Nocarte
																WHERE NomCours='Yoga')

-- 21b --
SELECT INSCRIT.Nom,INSCRIT.Nocarte
FROM PARTICIPATION JOIN INSCRIT INSCRIT1 ON PARTICIPATION.Nocarte = INSCRIT.Nocarte
WHERE PARTICIPATION.NomCours='Salsa' AND EXISTS	(	SELECT INSCRIT.Nocarte
													FROM PARTICIPATION JOIN INSCRIT INSCRIT2 ON PARTICIPATION.Nocarte = INSCRIT2.Nocarte
													WHERE NomCours='Yoga' AND INSCRIT2.Nocarte = INSCRIT1.Nocarte)

-- 22a --
SELECT NomCours, Jour
FROM PLANNING
WHERE NomCours not in (	SELECT NomCours
						FROM PLANNING
						WHERE Jour = 'mercredi' OR Jour ='lundi' )

-- 22b --
SELECT PLANNING1.NomCours, Jour
FROM PLANNING PLANNING1
WHERE NOT EXISTS (	SELECT PLANNING2.NomCours 
					FROM PLANNING PLANNING2
					WHERE (Jour = 'mercredi' OR Jour ='lundi') AND PLANNING1.NomCours = PLANNING2.NomCours)

-- 23a --
SELECT COURS.Enseignant
FROM COURS JOIN PLANNING on COURS.NomCours = PLANNING.NomCours
WHERE PLANNING.Jour = 'samedi' and COURS.Enseignant not in (	SELECT COURS.Enseignant
													FROM COURS JOIN PLANNING on COURS.NomCours = PLANNING.NomCours
													WHERE PLANNING.Jour = 'mardi')

-- 23b --
SELECT COURS1.Enseignant
FROM COURS COURS1 JOIN PLANNING on COURS1.NomCours = PLANNING.NomCours
WHERE PLANNING.Jour = 'samedi' and NOT EXISTS (SELECT COURS2.Enseignant
										FROM COURS COURS2 JOIN PLANNING on COURS2.NomCours = PLANNING.NomCours
										WHERE PLANNING.Jour = 'mardi' and COURS1.Enseignant = COURS2.Enseignant)

-- 24a --
SELECT DISTINCT NomCours 
FROM PLANNING
WHERE NomCours not in (	SELECT NomCours
						FROM PLANNING
						WHERE Jour != 'samedi' AND Jour !='jeudi' )

-- 24b --
SELECT DISTINCT I.NomCours
FROM PLANNING I
WHERE NOT EXISTS (	SELECT II.NomCours 
					FROM PLANNING II
					WHERE (Jour != 'samedi' AND Jour !='jeudi') AND I.NomCours = II.NomCours)

-- 25a --
SELECT DISTINCT PARTICIPATION.NomCours
FROM PARTICIPATION JOIN INSCRIT on PARTICIPATION.Nocarte = INSCRIT.Nocarte
WHERE PARTICIPATION.NomCours NOT IN (	SELECT PARTICIPATION.NomCours
										FROM PARTICIPATION JOIN INSCRIT on PARTICIPATION.Nocarte = INSCRIT.Nocarte
										WHERE INSCRIT.Age > 40)

-- 25b --
SELECT DISTINCT PARTICIPATION1.NomCours
FROM PARTICIPATION PARTICIPATION1 JOIN INSCRIT on PARTICIPATION1.Nocarte = INSCRIT.Nocarte
WHERE NOT EXISTS (	SELECT PARTICIPATION2.NomCours
					FROM PARTICIPATION PARTICIPATION2 JOIN INSCRIT on PARTICIPATION2.Nocarte = INSCRIT.Nocarte
					WHERE INSCRIT.Age > 40 AND PARTICIPATION1.NomCours = PARTICIPATION2.NomCours)


-- 26 --
SELECT NomCours
FROM PLANNING
WHERE Jour = 'samedi'
UNION
SELECT PLANNING.NomCours
	FROM PARTICIPATION JOIN INSCRIT on PLANNING.Nocarte = INSCRIT.Nocarte
	GROUP BY PLANNING.NomCours
	HAVING COUNT (*) <= 4

-- 27 --
SELECT NomCours
FROM COURS
WHERE Enseignant = 'Jean'
UNION
SELECT DISTINCT COURS.NomCours
	FROM COURS JOIN PLANNING on COURS.NomCours = PLANNING.NomCours 
	WHERE PLANNING.Heure > 15
